<a href="https://colab.research.google.com/github/19521242bao/Machine-Learning-Tutorial/blob/main/pttktt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!cat nacako1.csv

b,time
19520197,0.189
195201977,0.208
1952019777,0.221
19520197777,0.246
1.95202E+11,0.278
1.95202E+12,0.306
1.95202E+13,0.332
1.95202E+14,0.344
1.95202E+15,0.383
1.95202E+16,0.398
1.95202E+17,0.426
1.95202E+18,0.463
1.95202E+19,0.475
1.95202E+20,0.488
1.95202E+21,0.518
1.95202E+22,0.537
1.95202E+23,0.587
1.95202E+24,0.608
1.95202E+25,0.607
1.95202E+26,0.641
1.95202E+27,0.663
1.95202E+28,0.71
1.95202E+29,0.723
1.95202E+30,0.762
1.95202E+31,0.78
1.95202E+32,0.816
1.95202E+33,0.843
1.95202E+34,0.85
1.95202E+35,0.875
1.95202E+36,0.924


In [ ]:
import pandas as pd
data=pd.read_csv('nacako1.csv')
data.columns=['size','operation']
print (data)

            size  operation
0   1.952020e+07      0.189
1   1.952020e+08      0.208
2   1.952020e+09      0.221
3   1.952020e+10      0.246
4   1.952020e+11      0.278
5   1.952020e+12      0.306
6   1.952020e+13      0.332
7   1.952020e+14      0.344
8   1.952020e+15      0.383
9   1.952020e+16      0.398
10  1.952020e+17      0.426
11  1.952020e+18      0.463
12  1.952020e+19      0.475
13  1.952020e+20      0.488
14  1.952020e+21      0.518
15  1.952020e+22      0.537
16  1.952020e+23      0.587
17  1.952020e+24      0.608
18  1.952020e+25      0.607
19  1.952020e+26      0.641
20  1.952020e+27      0.663
21  1.952020e+28      0.710
22  1.952020e+29      0.723
23  1.952020e+30      0.762
24  1.952020e+31      0.780
25  1.952020e+32      0.816
26  1.952020e+33      0.843
27  1.952020e+34      0.850
28  1.952020e+35      0.875
29  1.952020e+36      0.924


In [ ]:
import numpy as np
X_=(data['size']).tolist()
X_

In [ ]:
X_=np.array(data['size']).reshape(-1,1)
X_

In [ ]:
Y_=np.array(data['operation']).reshape(-1,1)
Y_

In [ ]:
def sqrt_n(arr):
  return arr**(1/2)
sqrt_n(X_)

In [ ]:
def log2_n(arr):
  return np.log2(arr)
log2_n(X_)

array([[ 24.21846428],
       [ 27.54039242],
       [ 30.86232052],
       [ 34.18424862],
       [ 37.50617688],
       [ 40.82810497],
       [ 44.15003307],
       [ 47.47196116],
       [ 50.79388926],
       [ 54.11581735],
       [ 57.43774545],
       [ 60.75967354],
       [ 64.08160164],
       [ 67.40352973],
       [ 70.72545783],
       [ 74.04738592],
       [ 77.36931402],
       [ 80.69124211],
       [ 84.01317021],
       [ 87.3350983 ],
       [ 90.6570264 ],
       [ 93.97895449],
       [ 97.30088259],
       [100.62281068],
       [103.94473878],
       [107.26666687],
       [110.58859497],
       [113.91052306],
       [117.23245116],
       [120.55437925]])

In [ ]:
def n(arr):
  return arr
n(X_)

In [ ]:
def nlog2_n(arr):
  return arr*np.log2(arr)
nlog2_n(X_)

In [ ]:
def n2(arr):
  return arr**2
n2(X_)

In [ ]:
def n3(arr):
  return arr**3
n3(X_)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
model.fit(log2_n(X_),Y_)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model.coef_

array([[0.00757892]])

In [ ]:
model.intercept_

array([-0.00857786])

In [ ]:
def Print(x):
  x=str(x)
  length=len(str(x))-6
  List=[]
  List.append(x[:6])
  List.append('E+')
  List.append(str(len(x)-6))
  print(''.join(List))


In [ ]:
X_=data['size'].tolist()
for i in X_:
  t=int(str(i))
  giaithua=1
  while(t>1):
    giaithua*=t
    t-=1
  Print(giaithua)


In [ ]:
import pandas as pd
data1=pd.read_csv('data2.1.csv')
data1.columns=['size']
print (data1)

In [ ]:
X_=np.array(data1['size']).reshape(-1,1)
X_

In [ ]:
X_=data['size'].tolist()
for i in X_:
  Print(2**i)

In [ ]:
import math
from decimal import *
from sklearn.linear_model import LinearRegression
getcontext().prec=999999999999999
Decimal(math.factorial(99999999999))
model = LinearRegression()


In [ ]:
x_=data['size']
x_=np.array(x_,dtype=np.dtype(Decimal))
x_=[2**i for i in x_]
x_=np.reshape(x_,(-1,1))
print(x_)

In [ ]:
y_=data['operation']
y_=np.array(y_,dtype=np.dtype(Decimal))
y_=np.reshape(y_,(-1,1))
print(y_)

In [ ]:
model.fit(x_,y_)

In [ ]:
model.coef_

In [ ]:
model.intercept_

In [ ]:
!cat data2.csv

In [ ]:
import pandas as pd
data=pd.read_csv('data.csv')
data.columns=['size','operation']
print (data)

In [ ]:
def Print(a,list):
  a=str(a)
  length=len(str(a))-6
  lst=[]
  lst.append(a[:6])
  lst.append('e+')
  lst.append(str(len(a)-6))
  list.append(''.join(lst))

In [ ]:
import math
from decimal import *
getcontext().Emax=9999999999999
x_=data['size']
y_=data['operation']
t=x_.tolist()
t2=y_.tolist()
dem=0
for i in t:
  List=[]
  List.append(str(i))
  operation=t2[dem]
  List.append(str(operation))
  #k=0
  #tam=int(str(i))
  #giaithua=1.0
  #while tam > 1:
    #giaithua*=tam
    #tam-=1
  #Print(giaithua,List)
 # List.append(str(k)) #1*n!+0
  #Print((giaithua-operation)**2,List) #mse cua n!
  #List.append(str(k))
  List.append(giaithua_[dem-1])
  List.append(giaithua_[dem-1])

  dem+=1
  print(','.join(List))
